[workspace]

members = [
    "examples/diagram-box-only",
    "examples/nqueens",
    "local-search",
    "math-util",
]

[profile.release]
opt-level = 3

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
incremental = false