[workspace]

members = [
    "examples/diagram-box-only",
    "examples/nqueens",
    "local-search",
    "math-util",
]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false